# Generated by Django 5.0 on 2024-11-24 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_obra_opiniao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
    ]
